version: "3.8"

services:
  uploader:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3333:3333"
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
