name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libtesseract-dev \
          libleptonica-dev \
          tesseract-ocr-eng

    - name: Build
      run: go build -v ./...

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.45.2

    - name: Unit-test
      run: make unit-test
